# Generated by Django 5.0.3 on 2025-10-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('users_deleted', models.IntegerField()),
                ('active_users_remaining', models.IntegerField()),
            ],
        ),
    ]
